dbdata:
    image: postgres
    command: "true"

db:
    extends: 
        file: common.yml
        service: db_base
    volumes_from:
        - dbdata
    ports:
        - "9432:5432"
frontend:
    build: frontend/
    command: gulp develop
    ports:
        - "35729:35729"
    volumes:
        - "frontend/src:/src"
        - "frontend/dist:/dist"
        - "frontend/fonts:/fonts"
        - "frontend/images:/images"
        - "frontend/package.json:/package.json"
        - "frontend/bower.json:/bower.json"
        - "frontend/Gulpfile.js:/Gulpfile.js"
django:
    extends: 
        file: common.yml
        service: django_base
    ports:
        - "8000:8000"
    volumes:
        - "backend:/src"
        - "frontend/dist:/static"
        - "media:/media"
    links:
        - db
    environment:
        DJANGO_SETTINGS_MODULE: conf.settings
